## Numpy

In [1]:
import numpy as np

## Transposing Arrays and Swapping Axes

<img src = "https://ajcr.net/images/stride-guide/2d_array_b_example_transpose.png">

In [2]:
a = np.arange(4*3).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [4]:
a.T.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a.T.T.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [6]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [7]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

<img src="https://www.programmingsimplified.com/images/c/matrix-multiplication.png">

In [8]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
# (1*3)+(2*4)
arr1.dot(arr2)

11

<img src="http://media5.datahacker.rs/2020/04/Picture27-1024x386.jpg">

In [9]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b #dot Product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

<img src = "https://www.hebergementwebs.com/image/f8/f89a27be5d24abaf896d438100b6d127.jpg/algorithme-parallele-multiplication-matricielle-9.jpg">

In [10]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b) # dot Product

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [11]:
print(a, a.T, sep = "\n\n", end= "\n\n")

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]



In [12]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

<img src = "https://ajcr.net/images/stride-guide/3d_array_c_transpose.png">

In [13]:
a = np.arange(28).reshape((14,2))
print(a)
a.T

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]]


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27]])

In [14]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [15]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0) # column , row , slide

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

#### Swapping 

<img src = "https://media.geeksforgeeks.org/wp-content/uploads/20200826204614/swapnumpy.jpg">

In [16]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

## Unary ufuncs

In [17]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a) # return Absulote numbers eg: gradient decent optimizer /diatance

array([ 7,  8, 20,  2,  3, 20])

In [18]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

array([ 7.,  8., 20.,  2.,  3., 20.])

In [19]:
a = np.array([36,25,16])
np.fabs(a)

array([36., 25., 16.])

In [20]:
a = np.array([7,8,-20,2,-3,20])
np.square(a)

array([ 49,  64, 400,   4,   9, 400], dtype=int32)

**Example of Eular Formula**

In [21]:
np.exp(a)


array([1.09663316e+03, 2.98095799e+03, 2.06115362e-09, 7.38905610e+00,
       4.97870684e-02, 4.85165195e+08])

In [22]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [23]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [24]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [25]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [26]:
np.isnan(np.nan)

True

    0 = top to bottom
    1 = left to right

In [28]:
a = np.array([1])
b = np.array([3])

np.maximum(a,b)

array([3])

In [27]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.maximum(a,b)

array([3, 3, 5, 7])

In [33]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])
c = np.array([6,5,1,4])

np.maximum(a,b,c) #Result Is not correct for # array

array([3, 3, 5, 7])

In [37]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])
c = np.array([6,5,1,4])

np.fmax(a,b,c) #Result Is not correct for # array

array([3, 3, 5, 7])

In [42]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])
c = np.array([6,5,1,4])

np.maximum((a,b),c) 

array([[6, 5, 5, 7],
       [6, 5, 2, 4]])

## Array-Oriented Programming with Arrays

In [43]:
a = np.arange(4*3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**application of mesh grid**

In [44]:
np.meshgrid(np.array([1,2,3]),np.array([4,5,6]))

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5],
        [6, 6, 6]])]

In [45]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
np.meshgrid(a,np.array([1,2]))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])]

## Expressing Conditional Logic as Array Operations

#### np.where(condition, value_true, value_false)

In [47]:
a = np.arange(8*4).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

    np.where(condition, True_block, False_block)

In [48]:
np.where(a%3 == 0, "Yes","No")

array([['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No']], dtype='<U3')

In [49]:
np.where(a%3 == 0, a,0)

array([[ 0,  0,  0,  3],
       [ 0,  0,  6,  0],
       [ 0,  9,  0,  0],
       [12,  0,  0, 15],
       [ 0,  0, 18,  0],
       [ 0, 21,  0,  0],
       [24,  0,  0, 27],
       [ 0,  0, 30,  0]])

In [50]:
[[-1,0,1],
[-1,0,1],
[-1,0,1]] #less black more white in pic np array

[[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]

In [51]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

array([3, 3, 5, 7])