## Numpy...

In [1]:
import numpy as np

<img src="https://image.slidesharecdn.com/numpytalksiam-110305000848-phpapp01/95/numpy-talk-at-siam-17-728.jpg?cb=1299283822">

# Boolen Operation

In [2]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [3]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [4]:
print(a)
a[a%3==0] #InLine Operation 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
print(a)
a[(a%3==0) & (a%5==0)] #InLine Operation 

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [6]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [7]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [8]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [9]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

## Fancy Slicing

In [10]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


In [11]:
print(a)
a[1,2,0] #simple Slicing

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


25

In [12]:
print(a)
a[::-1]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
print(a)
a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]],

       [[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]]])

In [14]:
print(a)
a[[1,2,0]] # Fancy slicing ---> rearranging #InLine Operation

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
print(a)
a[[0,1,2],[0,1,2]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [16]:
print(a)
a[[0,1,2],[0,1,2],]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [17]:
print(a)
a[[0,1,2],[0,2,1],]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[10, 11, 12],
       [25, 26, 27],
       [31, 32, 33]])

In [18]:
print(a)
a[[1,2,0]][:,[2,1,0]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]],

       [[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]]])

In [19]:
print(a)
a[[1,2,0]][:,[-1,0]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[25, 26, 27],
        [19, 20, 21]],

       [[34, 35, 36],
        [28, 29, 30]],

       [[16, 17, 18],
        [10, 11, 12]]])

In [20]:
print(a)
a[[1,2,0]][:,[-1]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[25, 26, 27]],

       [[34, 35, 36]],

       [[16, 17, 18]]])

In [21]:
print(a)
a[[1,2,0]][:,::-1]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]],

       [[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]]])

In [22]:
print(a)
a[[1,2,0]][:,-1]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[25, 26, 27],
       [34, 35, 36],
       [16, 17, 18]])

In [23]:
print(a)
a[[1,2,0],:,::-1]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[21, 20, 19],
        [24, 23, 22],
        [27, 26, 25]],

       [[30, 29, 28],
        [33, 32, 31],
        [36, 35, 34]],

       [[12, 11, 10],
        [15, 14, 13],
        [18, 17, 16]]])

In [24]:
names = np.array(["Haseeb", "Qasim","Hamza","Ali","Haseeb","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

['Haseeb' 'Qasim' 'Hamza' 'Ali' 'Haseeb' 'Abid']


[[-0.35335504 -0.40870317  0.96536903 -0.28899005]
 [ 0.91845058 -0.88030149  0.57352464 -1.43854359]
 [-1.14500207 -0.11760955 -0.33798486  0.94183578]
 [-1.28767696 -1.26543878 -0.31787151  0.72086451]
 [-0.20786084 -2.2303597  -0.90535877 -0.80821837]
 [ 1.14365541 -1.56274807  1.15777277  0.6349042 ]]


In [25]:
names == "Haseeb"

array([ True, False, False, False,  True, False])

In [26]:
data[[ True, False, False, False,  True, False]]

array([[-0.35335504, -0.40870317,  0.96536903, -0.28899005],
       [-0.20786084, -2.2303597 , -0.90535877, -0.80821837]])

In [27]:
data[names=="Haseeb"]

array([[-0.35335504, -0.40870317,  0.96536903, -0.28899005],
       [-0.20786084, -2.2303597 , -0.90535877, -0.80821837]])

In [28]:
data[names=="Ali"]

array([[-1.28767696, -1.26543878, -0.31787151,  0.72086451]])

In [29]:
data[(names=="Haseeb") |  (names=="Abid")]

array([[-0.35335504, -0.40870317,  0.96536903, -0.28899005],
       [-0.20786084, -2.2303597 , -0.90535877, -0.80821837],
       [ 1.14365541, -1.56274807,  1.15777277,  0.6349042 ]])

In [30]:
data[(names!="Haseeb") |  (names=="Abid")]

array([[ 0.91845058, -0.88030149,  0.57352464, -1.43854359],
       [-1.14500207, -0.11760955, -0.33798486,  0.94183578],
       [-1.28767696, -1.26543878, -0.31787151,  0.72086451],
       [ 1.14365541, -1.56274807,  1.15777277,  0.6349042 ]])

In [31]:
data[(names!="Haseeb") |  (names!="Abid")]

array([[-0.35335504, -0.40870317,  0.96536903, -0.28899005],
       [ 0.91845058, -0.88030149,  0.57352464, -1.43854359],
       [-1.14500207, -0.11760955, -0.33798486,  0.94183578],
       [-1.28767696, -1.26543878, -0.31787151,  0.72086451],
       [-0.20786084, -2.2303597 , -0.90535877, -0.80821837],
       [ 1.14365541, -1.56274807,  1.15777277,  0.6349042 ]])

In [32]:
data[(names=="Haseeb") |  (names=="Abid")][:,-1]

array([-0.28899005, -0.80821837,  0.6349042 ])

In [33]:
data[(names=="Haseeb") |  (names=="Abid")][:,[-1]]

array([[-0.28899005],
       [-0.80821837],
       [ 0.6349042 ]])

In [34]:
data[(names=="Haseeb") |  (names=="Abid")][:,[0, -1]]

array([[-0.35335504, -0.28899005],
       [-0.20786084, -0.80821837],
       [ 1.14365541,  0.6349042 ]])

In [35]:
l = [1,3,5,3,5]
l[:3]
l[:3] = 5 #you can't assign more than 1 value without iteration in list

TypeError: can only assign an iterable

In [36]:
l = [1,3,5,3,5]
l[0] = 5
l

[5, 3, 5, 3, 5]

In [37]:
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5 #you can assign more than 1 value without iteration in np-array
l

array([5, 5, 5, 3, 5])

In [38]:
l

array([5, 5, 5, 3, 5])

In [39]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [40]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [41]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [42]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]
