## Numpy

<img src= "https://1.bp.blogspot.com/-3P-ULcc-aSc/XwINe8CjKgI/AAAAAAAAFFg/LhApCVa2YqUBlnqDDNW4NudSS398L5gjACLcBGAsYHQ/s640/NumPy%2Barrays.png">

#### A Multidimensional Array Object

In [1]:
import numpy as np

In [2]:
l1 = np.arange(1,13)
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
l1.shape

(12,)

In [15]:
np.arange(1,13).reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
np.arange(1,13).reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [17]:
np.arange(1,13).reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
# l1 = np.arange(1,13).reshape((4,3))
# l1 = np.arange(1,13).reshape((3,4))
# l1 = np.arange(1,13).reshape((2,6))
# l1 = np.arange(1,13).reshape((6,2))
# l1 = np.arange(1,13).reshape((12,1))

l1 = np.arange(1,13).reshape((2,-1))  # -1 is used for getting automatic possible row/col value 

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (2, 6)


<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

    l1[i,j,k]
    l1[slide, row, column]

<img src="https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg">

**..0D..---..1D..---..2D..---....3D.....---...........4D.............---.............5D............**


**Scalar---Vector---Matrix---Tensor/Cube---Vector Of Tensor's/Cube's ---Matrix Of Tensor's/Cube's**

In [20]:
np.arange(4*3*2*2).reshape(4,3,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [24]:
np.arange(4*3*2*2).reshape(4,-1,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43]],

        [[44, 45],
         [46, 47]]]])

In [25]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [26]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
# l1[2]
# l1[1,2]
#l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [28]:
l1[2]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [27]:
l1[1,2]

array([16, 17, 18])

In [29]:
l1[1,2,1]

17

In [30]:
l1 = np.array(['a','b','c'])
print(l1)
#    0     1    2
print(l1[[True,True,False]])
print(l1[[True,False,True]])

['a' 'b' 'c']
['a' 'b']
['a' 'c']


In [31]:
ages = np.arange(1,50)
adult = []
for age in ages:
    if age >18:
        adult.append(True)
    else:
        adult.append(False)
adult

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [32]:
ages[adult]

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
adult = [True for age in ages if age>18] #this wil only return only true but we want bith false n true.So,
adult

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [43]:
adult = [True if age>18 else False for age in ages]
adult

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [44]:
ages[adult]

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
ages[ages>18] #more easy way

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [45]:
l1 = np.arange(1,28).reshape((3,3,3))
l1[l1 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [47]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 0.60434866 -2.1567893  -0.98187692]
  [ 0.70470571  0.21389226 -0.66648082]
  [ 0.39729536 -1.05403895 -0.61506565]]

 [[-0.02392788 -0.96798252  0.55706858]
  [ 1.41084098 -0.91185321  0.19911531]
  [ 0.31824538  0.7598981  -0.67912959]]

 [[ 0.8040931  -0.38511045  0.88573081]
  [-0.31330812  1.5271861  -2.0043007 ]
  [ 0.30096486 -0.72093225 -1.57820143]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [48]:
l1 + 2

#
#
#
#

array([[[ 2.60434866, -0.1567893 ,  1.01812308],
        [ 2.70470571,  2.21389226,  1.33351918],
        [ 2.39729536,  0.94596105,  1.38493435]],

       [[ 1.97607212,  1.03201748,  2.55706858],
        [ 3.41084098,  1.08814679,  2.19911531],
        [ 2.31824538,  2.7598981 ,  1.32087041]],

       [[ 2.8040931 ,  1.61488955,  2.88573081],
        [ 1.68669188,  3.5271861 , -0.0043007 ],
        [ 2.30096486,  1.27906775,  0.42179857]]])

In [52]:
l1 * 2

array([[[ 1.20869732, -4.3135786 , -1.96375383],
        [ 1.40941143,  0.42778452, -1.33296165],
        [ 0.79459072, -2.10807791, -1.23013131]],

       [[-0.04785576, -1.93596504,  1.11413716],
        [ 2.82168196, -1.82370643,  0.39823063],
        [ 0.63649076,  1.5197962 , -1.35825919]],

       [[ 1.60818621, -0.7702209 ,  1.77146162],
        [-0.62661624,  3.05437219, -4.0086014 ],
        [ 0.60192972, -1.44186449, -3.15640287]]])

In [53]:
l1 / 2

array([[[ 0.30217433, -1.07839465, -0.49093846],
        [ 0.35235286,  0.10694613, -0.33324041],
        [ 0.19864768, -0.52701948, -0.30753283]],

       [[-0.01196394, -0.48399126,  0.27853429],
        [ 0.70542049, -0.45592661,  0.09955766],
        [ 0.15912269,  0.37994905, -0.3395648 ]],

       [[ 0.40204655, -0.19255522,  0.44286541],
        [-0.15665406,  0.76359305, -1.00215035],
        [ 0.15048243, -0.36046612, -0.78910072]]])

In [54]:
l1 ** 2

array([[[3.65237302e-01, 4.65174009e+00, 9.64082280e-01],
        [4.96610144e-01, 4.57498992e-02, 4.44196688e-01],
        [1.57843603e-01, 1.11099811e+00, 3.78305757e-01]],

       [[5.72543401e-04, 9.36990157e-01, 3.10325401e-01],
        [1.99047227e+00, 8.31476283e-01, 3.96469084e-02],
        [1.01280121e-01, 5.77445126e-01, 4.61217006e-01]],

       [[6.46565718e-01, 1.48310057e-01, 7.84519071e-01],
        [9.81619775e-02, 2.33229737e+00, 4.01722130e+00],
        [9.05798475e-02, 5.19743305e-01, 2.49071977e+00]]])

In [55]:
l1 ** 0.5 # under-root

<ipython-input-55-cb55cb0a98bf>:1: RuntimeWarning: invalid value encountered in sqrt
  l1 ** 0.5


array([[[0.77739865,        nan,        nan],
        [0.83946752, 0.46248488,        nan],
        [0.6303137 ,        nan,        nan]],

       [[       nan,        nan, 0.74637027],
        [1.18778827,        nan, 0.44622339],
        [0.56413241, 0.87172134,        nan]],

       [[0.89671239,        nan, 0.94113273],
        [       nan, 1.23579371,        nan],
        [0.54860264,        nan,        nan]]])

In [58]:
l1 % 2

array([[[0.60434866, 1.8432107 , 1.01812308],
        [0.70470571, 0.21389226, 1.33351918],
        [0.39729536, 0.94596105, 1.38493435]],

       [[1.97607212, 1.03201748, 0.55706858],
        [1.41084098, 1.08814679, 0.19911531],
        [0.31824538, 0.7598981 , 1.32087041]],

       [[0.8040931 , 1.61488955, 0.88573081],
        [1.68669188, 1.5271861 , 1.9956993 ],
        [0.30096486, 1.27906775, 0.42179857]]])

In [59]:
l1 % 2 == 0

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])