## Numpy...

In [1]:
import numpy as np

## Creating ndarrays

**np.array()**

In [3]:
l = [1, 2, 3]

l1 = np.array(l)
l2 = np.array(l1)

print(l1)
print(l2)

print(l1 is l2) #False
print(l2 is l1) #False
print(id(l1) == id(l1))
print(id(l1) == id (l2))

[1 2 3]
[1 2 3]
False
False
True
False


**np.asarray()**

In [12]:
# 1 array->Same dtype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(l,a,b,c, sep = ' ')
print(a is b) # 2
print(a is l) # 1
print(a is c) # 3

print(type(l))
print(a.dtype)
print(b.dtype)
print(c.dtype)


<class 'list'>
[1, 2, 3] [1 2 3] [1 2 3] [1. 2. 3.]
True
False
False
<class 'list'>
int32
int32
float64


In [13]:
import numpy as np
a = np.array([1,2])
print(a)
a.itemsize

[1 2]


4

**np.arange()**

In [14]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

## Chaining

In [15]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [16]:
C(B(A(1))) # 5+1=6  6+6=12 12+7=19

19

In [17]:
A(B(C(1)))

19

**np.A().B().C()**

    #arange().reshape()
    #np.ones
    #np.ones_like
    #np.zeros
    #np.zeros_like
    #np.full
    #np.full_like
    #np.empty
    #np.empty_like

In [18]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [19]:
b = np.reshape(a, (27,1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [20]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9) # You can change shape as per you need becuase it's not private # IN MEMORY
a.reshape(3,3,3) # becuase of INLINE funstion didn't changes the shape
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [21]:
a = a.reshape(3,3,3) #Now it will be in in memory
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [22]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [23]:
a.shape

(9, 3)

In [24]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
#we required Same size of array containing zero as any pic or array have
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a.shape

(9, 3)

In [28]:
np.zeros(a.shape) # return in float

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros_like(a) # return integers

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [31]:
b = np.ones((3,3)) # in float
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
b = np.ones_like(a) # in integer
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
b = np.ones_like(a) * 5  + 5
b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [41]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [42]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [43]:
np.full_like(a, dtype=a.dtype, fill_value=2.5) #dtype of a is int64

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [44]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [45]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [47]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
np.full_like(a, 1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [51]:
np.full_like(a, 1) * np.nan


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [52]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [53]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [54]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data Types for ndarrays

In [55]:
a = np.array([1,3,4], dtype='int')
a.dtype


dtype('int32')

In [56]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int32')

In [57]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [58]:
a = np.array([1,3,4], dtype='i8')
a.dtype

dtype('int64')

In [59]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int64')

In [60]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

In [ ]:
#Continue...