## Numpy...

In [1]:
import numpy as np

## Mathematical and Statistical Methods

In [2]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.sum(a)

66

In [4]:
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [5]:
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

#### Broad Casting

converting small array to large array...

In [6]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
# backend working when we pperform + on np_array...
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 5)
print(a,b,sep="\n\n")
a + b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## Stacking
- stacking ->axis 0(horzental), 1(verticle)
- vstack
- columnstack
- hstack
- rowstack
- block
- dstack

In [8]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[7 3 3 8 2 8 3 7 8 9]
[12  8  8 13  7 13  8 12 13 14]
10 10


In [9]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

[7 3 3 8 2 8 3 7 8 9]

[12  8  8 13  7 13  8 12 13 14]


array([[ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9],
       [12,  8,  8, 13,  7, 13,  8, 12, 13, 14]])

In [10]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

[7 3 3 8 2 8 3 7 8 9]

[12  8  8 13  7 13  8 12 13 14]


array([[ 7, 12],
       [ 3,  8],
       [ 3,  8],
       [ 8, 13],
       [ 2,  7],
       [ 8, 13],
       [ 3,  8],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14]])

In [11]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

array([[ 7, 12],
       [ 3,  8],
       [ 3,  8],
       [ 8, 13],
       [ 2,  7],
       [ 8, 13],
       [ 3,  8],
       [ 7, 12],
       [ 8, 13],
       [ 9, 14]])

In [12]:
# np.stack((a,b), axis=1)
np.row_stack((a,b))

array([[ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9],
       [12,  8,  8, 13,  7, 13,  8, 12, 13, 14]])

In [14]:
np.stack((a,b), axis=0)

array([[ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9],
       [12,  8,  8, 13,  7, 13,  8, 12, 13, 14]])

In [15]:
np.vstack((a,b))

array([[ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9],
       [12,  8,  8, 13,  7, 13,  8, 12, 13, 14]])

In [16]:
np.hstack((a,b))

array([ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9, 12,  8,  8, 13,  7, 13,  8,
       12, 13, 14])

In [17]:
np.vstack((a,b))

array([[ 7,  3,  3,  8,  2,  8,  3,  7,  8,  9],
       [12,  8,  8, 13,  7, 13,  8, 12, 13, 14]])

In [18]:
b = np.arange(3*3).reshape((3,3)) 
a = b + 5
print(a, b, sep='\n\n')

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
np.vstack((a,b)) # vertically 

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [20]:
np.hstack((a,b)) # horizentally

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [21]:
np.column_stack((a,b))

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [22]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b)) # DEPTH STACKING  with slide through depth

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1,  7,  8],
        [ 2,  3,  9, 10]],

       [[ 4,  5, 11, 12],
        [ 6,  7, 13, 14]]])

## Split

In [23]:
a = np.arange(6*6).reshape((6,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [24]:
print(a)
np.split(a, 6, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [25]:
print(a)
np.split(a, 3, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [26]:
print(a)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [27]:
print(a)
np.split(a, 2, axis=0)[0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [28]:
np.dsplit?? #depth split for 3d array n above

In [29]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

## Array set operations

In [30]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[6 1 6 4 3 3 2 3 2 8 1 9 6 1 9 2 5 6 6 6]


array([1, 2, 3, 4, 5, 6, 8, 9])

In [31]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


**[true_block  if condition else fasle_block for x in data]**

In [33]:
[  True if x in piaic else False for x in cnic]

[False, False, False, False, True]

In [35]:
[x in piaic for x in cnic]

[False, False, False, False, True]

In [36]:
["Yes" if x in piaic else "NO" for x in cnic]

['NO', 'NO', 'NO', 'NO', 'Yes']

In [37]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)


[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array([False, False, False, False,  True])

In [38]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
np.where(c==True,"Yes","No")

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array(['No', 'No', 'No', 'No', 'Yes'], dtype='<U3')

In [39]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array([7])

In [40]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array([ 2,  3,  4,  6,  7,  8, 10, 12, 18, 20, 23, 35, 39, 45, 58, 61, 67,
       69, 73, 74, 88, 90, 91, 92, 94, 95, 98])

In [41]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array([3, 4, 8])

In [42]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)

[98 74 95 23  7 10 67 61 94 88 12 91  2 18 92 58 94 67 20 69 45  6 73 35
 35 18 58  7 39 90]

[3 4 8 4 7]


array([ 2,  3,  4,  6,  8, 10, 12, 18, 20, 23, 35, 39, 45, 58, 61, 67, 69,
       73, 74, 88, 90, 91, 92, 94, 95, 98])

In [43]:
import numpy as np

a = np.arange(4).reshape(2 , 2)
print(a)

b = np.arange(4,8).reshape(2,2)
print(b)

c = np.arange(9,13).reshape(2,2)
print(c)

np.vstack((a, b,c))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 9 10]
 [11 12]]


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 9, 10],
       [11, 12]])